services:
  cadastro-api:
    build:
      context: ./api
      target: dev
    command: pnpm run dev
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    ports:
      - "3333:3333"
    volumes:
      - './api:/api'
      - '/api/node_modules'
    depends_on:
      - cadastro-database
    networks:
      - cadastro-networks

  cadastro-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - './frontend:/frontend'
    networks:
      - cadastro-networks
  cadastro-database:
    image: bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASS}
      POSTGRESQL_DATABASE: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - cadastro-networks
  gateway:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - cadastro-api
      - cadastro-frontend

    networks:
      - cadastro-networks

volumes:
  postgres_data:


networks:
  cadastro-networks:
    driver: bridge
