services:
  cadastro-api:
    build: ./api
    ports:
      - "3333:3333"
    networks:
      - cadastro-networks

  cadastro-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - cadastro-networks
  gateway:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - cadastro-networks

networks:
  cadastro-networks:
    driver: bridge
