services:
  cadastro-api:
    build: ./api
    ports:
      - "3333:3333"
    networks:
      - cadastro-networks

  cadastro-frontend:
    build: ./cadastro
    ports:
      - "3000:3000"
    networks:
      - cadastro-networks

networks:
  cadastro-networks:
    driver: bridge